FORMAT: 1A
HOST: http://curiosity.com/api

# Appreciations

A simple API to interact with the appreciations for C2.

## Apprecaitions Collection [/v1/appreciations/{?offset,limit}]



### Get a list of all Appreciations [GET]

Gives a JSON array containing a list of the appreciations. 


+ Parameters
    + offset (number) - The offset; Eg: 0 would be the first offset
    + limit (number) - The number of apprecations requested; Eg: 50


+ Response 200 (application/json)

        {
            "pagination":{
                            "offset": 0,
                            "limit": 2,
                            "total": 1001
                        },
            "appreciations":[   
                                {
                                    "id":1,
                                    "text": "Congratulations on getting your first paper presented at BIAKM 2016. The whole team has done a wonderful job",
                                    "author": "Dr.Asha Nayak",
                                    "category":"general",
                                    "reactions":{
                                                    "thumbsup": 23, 
                                                    "heart":12,
                                                    "heavy_plus_sign":34
                                                },
                                    "usersTagged": [
                                                        {
                                                            "name": "Jennifer Johnson",
                                                            "id": "1001"
                                                        }, {
                                                            "name": "Arjun Altaf",
                                                            "id": "1002"
                                                        }, {
                                                            "name": "Michale Moore",
                                                            "id": "1003"
                                                        }, {
                                                            "name": "Rahul Randhawa",
                                                            "id": "1004"
                                                        }
                                                    ]
                                }, 
                                {
                                    "id":2,
                                    "text": "I want to express my gratitute to the party planning commitee for the wonderful Diwali Celebrations we had at our Univeristy",
                                    "category":"general",
                                    "author": "Michael Scott",
                                    "reactions":{
                                                    "thumbsup": 4, 
                                                    "heart":100,
                                                    "heavy_plus_sign":2
                                                },
                                    "usersTagged": [
                                                        {
                                                            "name": "Angela Martin",
                                                            "id": "2001"
                                                        }, {
                                                            "name": "Phyllis Lapin",
                                                            "id": "2002"
                                                        }, {
                                                            "name": "Meredith Palmer",
                                                            "id": "2003"
                                                        }, {
                                                            "name": "Pam Beesly",
                                                            "id": "2004"
                                                        }
                                                    ]
                                }
                            ]
        }
        
### Save an appreciation [POST]

Takes a JSON object containing a text string as the appreciations
and a array of users who the appreciation refers to.

+ Request (application/json)

        {
            "text": "Thanks for saving my life and the city of New York once again!",
            "author": "April O'Neil",
            "category":"general",
            "usersTagged": [
                                {
                                    "name": "Leonardo",
                                    "id": "3001"
                                }, {
                                    "name": "Donatello",
                                    "id": "3002"
                                }, {
                                    "name": "Michelangelo",
                                    "id": "3003"
                                }, {
                                    "name": "Raphael",
                                    "id": "3004"
                                }
                            ]
        }

+ Response 200 (application/json)

    + Headers

    + Body

            {
                "id":3,
                "text": "Thanks for saving my life and the city of New York once again!"
                "author": "April O'Neil",
                "category":"general",
                "reactions":{
                                "thumbsup": 0, 
                                "heart":0,
                                "heavy_plus_sign":0
                            },
                "usersTagged": [
                                    {
                                        "name": "Leonardo",
                                        "id": "3001"
                                    }, {
                                        "name": "Donatello",
                                        "id": "3002"
                                    }, {
                                        "name": "Michelangelo",
                                        "id": "3003"
                                    }, {
                                        "name": "Raphael",
                                        "id": "3004"
                                    }
                                ]
                "created_at": "2016-09-05T08:40:51.620Z",
            }
            


## Apprecaition [/v1/appreciation/{appreciation_id}]

+ Parameters
    + appreciation_id (number) - ID of the appreciation in the form of an integer

### Get an appreciation [GET]

Gives a JSON object containing an appreciation for the requested id. 

+ Response 200 (application/json)

        {
            "id":1,
            "text": "Congratulations on getting your first paper presented at BIAKM 2016. The whole team has done a wonderful job",
            "category":"general",
            "author": "Dr.Asha Nayak",
            "reactions":{
                            "thumbsup": 23, 
                            "heart":12,
                            "heavy_plus_sign":34
                        },
            "usersTagged": [
                                {
                                    "name": "Jennifer Johnson",
                                    "id": "1001"
                                }, {
                                    "name": "Arjun Altaf",
                                    "id": "1002"
                                }, {
                                    "name": "Michale Moore",
                                    "id": "1003"
                                }, {
                                    "name": "Rahul Randhawa",
                                    "id": "1004"
                                }
                            ]
        }

### Edit an appreciation [PUT]

Takes a JSON object containing the id of the appreciation to edit along with
a text string as the appreciations, the reactions object, and a array of 
users who the appreciation refers to.

+ Request (application/json)

        {
            "id":3,
            "text": "Thanks for saving our life and the city of New York once again!",
            "category":"general",
            "author": "April O'Neil",
            "reactions":{
                                "thumbsup": 10, 
                                "heart":15,
                                "heavy_plus_sign":20
                            },
            "usersTagged": [
                                {
                                    "name": "Leonardo",
                                    "id": "3001"
                                }, {
                                    "name": "Donatello",
                                    "id": "3002"
                                }, {
                                    "name": "Michelangelo",
                                    "id": "3003"
                                }, {
                                    "name": "Raphael",
                                    "id": "3004"
                                }
                            ]
        }

+ Response 200 (application/json)

    + Headers

    + Body

            {
                "id":3,
                "text": "Thanks for saving my life and the city of New York once again!"
                "author": "April O'Neil",
                "category":"general",
                "reactions":{
                                "thumbsup": 10, 
                                "heart":15,
                                "heavy_plus_sign":20
                            },
                "usersTagged": [
                                    {
                                        "name": "Leonardo",
                                        "id": "3001"
                                    }, {
                                        "name": "Donatello",
                                        "id": "3002"
                                    }, {
                                        "name": "Michelangelo",
                                        "id": "3003"
                                    }, {
                                        "name": "Raphael",
                                        "id": "3004"
                                    }
                                ]
                "created_at": "2016-09-05T08:40:51.620Z",
            }

### Delete [DELETE]

Delets the appreciation for the given id. 

+ Response 204